#!/usr/bin/env node
// 品牌像素头像生成器：字符画 → 16×16 crispEdges SVG（src/brands/<key>.svg）。
// 用法：node tools/gen-brands.mjs
// 加新品牌 = 在 BRANDS 里加一段字符画 + 调色板，重跑本脚本。
// 字符画每行 16 字符；'.' = 透明；其余字符查调色板。

import { writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const outDir = path.join(root, 'src/brands');
mkdirSync(outDir, { recursive: true });

function toSvg(art, palette, key) {
  if (art.length !== 16 || art.some((row) => row.length !== 16)) {
    throw new Error(`${key}: 画布必须为 16×16`);
  }
  const rects = [];
  art.forEach((row, y) => {
    for (let x = 0; x < 16; x++) {
      const ch = row[x];
      if (ch === '.') continue;
      const fill = palette[ch];
      if (!fill) throw new Error(`${key}: 字符 "${ch}" 无对应颜色`);
      rects.push(`    <rect x="${x}" y="${y}" width="1" height="1" fill="${fill}"/>`);
    }
  });
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" shape-rendering="crispEdges">
  <!-- generated by tools/gen-brands.mjs -->
  <g>
${rects.join('\n')}
  </g>
</svg>
`;
}

const BRANDS = {
  // DeepSeek Harness —— 蓝鲸「大肥鱼」
  dsh: {
    palette: { '#': '#123a5c', B: '#2d7ab8', L: '#8ecae6', W: '#cfe8f7', E: '#08263f', S: '#dff3fb', F: '#1b5680' },
    art: [
      '................',
      '................',
      '..........S.....',
      '.........SSS....',
      '.........S.S....',
      '...#########....',
      '..#BBBBBBBBB#...',
      '.#BBBBBBBBBBB#..',
      '#BBBBBBBBBBBBB#.',
      '#BBBWWBBBBBEEB#.',
      '#BBWWBBBBBBBBB#.',
      '#BBBBBBBBBBBB#..',
      '#BLLLLLLLLBB#...',
      '.#LLLLLLLLL#....',
      '..##.###.##.....',
      '.#F#.....#F#....',
    ],
  },

  // 兜底：终端窗口 + 绿色提示符
  generic: {
    palette: { '#': '#5c4a32', R: '#c0392b', K: '#1e2b1e', G: '#4ade80', D: '#22c55e' },
    art: [
      '................',
      '..############..',
      '.#RRRRRRRRRRRR#.',
      '.##############.',
      '.#KKKKKKKKKKKK#.',
      '.#KKKKKKKKKKKK#.',
      '.#KKGKKKKKKKKK#.',
      '.#KKKGGKKKKKKK#.',
      '.#KKKKKDDDDKKK#.',
      '.#KKKKKKKKKKKK#.',
      '.#KKKKKKKKKKKK#.',
      '.#KKKKKKKKKKKK#.',
      '.#KKKKKKKKKKKK#.',
      '.##############.',
      '..############..',
      '................',
    ],
  },

  // Claude Code —— 橙色放射星芒
  'claude-code': {
    palette: { '#': '#b3452a', O: '#e8825e', Y: '#f4b48a', W: '#fbe3d0' },
    art: [
      '................',
      '.......##.......',
      '.......##.......',
      '......#OO#......',
      '.......##.......',
      '.......##.......',
      '..##...##...##..',
      '.#OO##.#Y.##OO#.',
      '..#O#.#YY#.#O#..',
      '...#.##WW##.#...',
      '....##YYYY##....',
      '...#..#YY#..#...',
      '..#O#.#YY#.#O#..',
      '.#OO##.#Y.##OO#.',
      '..##...##...##..',
      '.......##.......',
    ],
  },

  // OpenAI Codex —— 六瓣花结（简化为原子环）
  codex: {
    palette: { '#': '#0d2440', O: '#10a37f', W: '#e6f6f1' },
    art: [
      '................',
      '.....######.....',
      '...##OOOOOO##...',
      '..#OOOWWWWOOO#..',
      '..#OOW#..#WOO#..',
      '.#OOW#....#WOO#.',
      '.#OW#..##..#WO#.',
      '.#OW#.#WW#.#WO#.',
      '.#OOW#....#WOO#.',
      '..#OOW#..#WOO#..',
      '..#OOOWWWWOOO#..',
      '...##OOOOOO##...',
      '.....######.....',
      '................',
      '................',
      '................',
    ],
  },

  // Gemini CLI —— 四芒星
  'gemini-cli': {
    palette: { '#': '#3b4fd8', O: '#5b76f0', W: '#aebfff', P: '#9b72cb' },
    art: [
      '................',
      '.......##.......',
      '.......##.......',
      '......#OO#......',
      '......#OO#......',
      '.....#OWWO#.....',
      '.....#OWWO#.....',
      '..####WWWW####..',
      '.#OOOWWPPWWWOO#.',
      '..####WWWW####..',
      '.....#OWWO#.....',
      '.....#OWWO#.....',
      '......#OO#......',
      '......#OO#......',
      '.......##.......',
      '................',
    ],
  },

  // Cursor —— 紫色光标箭头
  cursor: {
    palette: { '#': '#2f2340', O: '#7c5cff', W: '#c9baff', H: '#e3f2fa' },
    art: [
      '................',
      '..##............',
      '..#O#...........',
      '..#OO#..........',
      '..#OWO#.........',
      '..#OWWO#........',
      '..#OWWWO#.......',
      '..#OWWWWO#......',
      '..#OWWWWWO#.....',
      '..#OWWWWWWO#....',
      '..#OWWHHWWO#....',
      '..#OW#HH#WO#....',
      '..#OO##.##O#....',
      '..#OO#..#O#.....',
      '..###..##O#.....',
      '.......###......',
    ],
  },

  // OpenCode —— 方环芯片
  opencode: {
    palette: { '#': '#1c2733', O: '#f97316', W: '#fed7aa', G: '#94a3b8' },
    art: [
      '................',
      '...G........G...',
      '....########....',
      '..G#OOOOOOOO#G..',
      '...#O######O#...',
      '...#O#WWWW#O#...',
      '.G.#O#W##W#O#.G.',
      '...#O#W##W#O#...',
      '...#O#WWWW#O#...',
      '..G#O######O#G..',
      '...#OOOOOOOO#...',
      '....########....',
      '...G........G...',
      '................',
      '................',
      '................',
    ],
  },

  // Goose —— 白鹅
  goose: {
    palette: { '#': '#4a4436', W: '#f5f0e6', O: '#f59e0b', E: '#1c1917', G: '#e7e0cf' },
    art: [
      '................',
      '................',
      '.....##.........',
      '....#WW#..##....',
      '....#WW##WW#....',
      '....#WWEWWW#....',
      '.....#WWWW#.....',
      '#....#WWWW#.....',
      '#O##.#WWWW#.....',
      '.#OWWWWWWWW#....',
      '..#WWWWWWWWW#...',
      '..#WWWWWWWWW#...',
      '...#WWWWWWW#....',
      '...#W##W##W#....',
      '....#..#..#.....',
      '................',
    ],
  },

  // Amp —— 闪电
  amp: {
    palette: { '#': '#1a2b4a', O: '#22d3ee', W: '#a5f3fc' },
    art: [
      '................',
      '.......###......',
      '......#OOO#.....',
      '.....#OOO#......',
      '....#OOO#.......',
      '...#OOO#........',
      '..#OOO#####.....',
      '.#OOOOOOOOO#....',
      '..####OOOO#.....',
      '......#OO#......',
      '.....#OO#.......',
      '....#OO#........',
      '...#OO##........',
      '..#OO#..........',
      '..##............',
      '................',
    ],
  },

  // GitHub Copilot —— 头盔脸
  copilot: {
    palette: { '#': '#24292f', O: '#3c434d', W: '#8b949e', E: '#58a6ff' },
    art: [
      '................',
      '....########....',
      '..##OOOOOOOO##..',
      '..#OOOOOOOOOO#..',
      '.#OOOOOOOOOOOO#.',
      '.#OO##OOOO##OO#.',
      '.#OOEEOOOOEEOO#.',
      '.#OOEEOOOOEEOO#.',
      '.#OOOOOOOOOOOO#.',
      '.#OOOOOOOOOOOO#.',
      '..#OOOOOOOOOO#..',
      '..#OOOWWWWOOO#..',
      '...#OOOOOOOO#...',
      '....########....',
      '................',
      '................',
    ],
  },

  // Aider —— 棋子
  aider: {
    palette: { '#': '#3d2b1f', O: '#d97706', W: '#fde68a', G: '#92400e' },
    art: [
      '................',
      '.....######.....',
      '....#OOOOOO#....',
      '...#OOWWWWOO#...',
      '...#OOWWWWOO#...',
      '....#OOOOOO#....',
      '.....#OOOO#.....',
      '.....#OOOO#.....',
      '....#OOOOOO#....',
      '...#OOGGGGOO#...',
      '..#OOOGGGOOOO#..',
      '.#OOOOOGGOOOOO#.',
      '..##############',
      '..##############',
      '................',
      '................',
    ],
  },
};

for (const [key, { art, palette }] of Object.entries(BRANDS)) {
  const svg = toSvg(art, palette, key);
  const file = path.join(outDir, `${key}.svg`);
  writeFileSync(file, svg);
  console.log(`ok ${file}`);
}
console.log(`generated ${Object.keys(BRANDS).length} brand avatars`);
