#!/usr/bin/env node
// 品牌像素头像生成器（src/brands/<key>.svg，16×16 crispEdges SVG）。
//
// 两级来源：
// 1. simple-icons（CC0）正牌轮廓 → 160×160 栅格化 → 盒降采样 16×16 →
//    品牌色填充 + 自动对比描边（暗色品牌描白边、亮色品牌描黑边，
//    保证深浅主题底上都可读）。依赖 puppeteer-core 栅格化（须在仓库内运行）。
// 2. 无收录的品牌（dsh 自家、OpenAI 系商标未收录等）→ 手绘字符画。
//
// 用法：node tools/gen-brands.mjs
// 加新品牌：优先在 SIMPLE_ICONS 加 slug；无收录再画字符画。

import { writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import puppeteer from 'puppeteer-core';
import * as icons from 'simple-icons';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const outDir = path.join(root, 'src/brands');
mkdirSync(outDir, { recursive: true });

// ---- 1. simple-icons 正牌像素化 ----

// 品牌 key → simple-icons 导出名（si + 标题去空格）
const SIMPLE_ICONS = {
  'claude-code': 'siClaudecode',
  copilot: 'siGithubcopilot',
  cursor: 'siCursor',
  'gemini-cli': 'siGooglegemini',
  opencode: 'siOpencode',
};

/** 相对亮度（0..1） */
function luminance(hex) {
  const n = parseInt(hex.slice(1), 16);
  const [r, g, b] = [(n >> 16) & 255, (n >> 8) & 255, n & 255].map((c) => c / 255);
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

/** 浏览器内栅格化：SVG path → 160×160 → 盒降采样 16×16 墨点矩阵 */
async function rasterize(page, svgPath, hex) {
  return page.evaluate(
    (svgPath, hex) => {
      const HI = 160; // 16 的 10 倍，每格 10×10 采样
      const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="${svgPath}" fill="#${hex}"/></svg>`;
      const url = `data:image/svg+xml;base64,${btoa(svg)}`;
      const img = new Image();
      img.src = url;
      return new Promise((resolve) => {
        img.onload = () => {
          const canvas = document.createElement('canvas');
          canvas.width = HI;
          canvas.height = HI;
          const ctx = canvas.getContext('2d', { willReadFrequently: true });
          ctx.drawImage(img, 0, 0, HI, HI);
          const data = ctx.getImageData(0, 0, HI, HI).data;
          const grid = [];
          for (let y = 0; y < 16; y++) {
            const row = [];
            for (let x = 0; x < 16; x++) {
              let ink = 0;
              for (let sy = 0; sy < 10; sy++) {
                for (let sx = 0; sx < 10; sx++) {
                  const i = ((y * 10 + sy) * HI + x * 10 + sx) * 4 + 3;
                  if (data[i] > 127) ink++;
                }
              }
              row.push(ink >= 50 ? 1 : 0); // ≥50% 覆盖才算墨
            }
            grid.push(row);
          }
          resolve(grid);
        };
        img.onerror = () => resolve(null);
      });
    },
    svgPath,
    hex
  );
}

/** 墨点矩阵 → 像素 SVG：内部品牌色 + 外缘对比描边 */
function gridToSvg(grid, hex) {
  const outline = luminance(hex) < 0.5 ? '#ffffff' : '#101010';
  const at = (x, y) => (x < 0 || y < 0 || x > 15 || y > 15 ? 0 : grid[y][x]);
  const rects = [];
  for (let y = 0; y < 16; y++) {
    for (let x = 0; x < 16; x++) {
      if (!grid[y][x]) continue;
      const isEdge = !at(x - 1, y) || !at(x + 1, y) || !at(x, y - 1) || !at(x, y + 1);
      rects.push({ x, y, fill: isEdge ? outline : `#${hex}` });
    }
  }
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" shape-rendering="crispEdges">
  <!-- generated by tools/gen-brands.mjs (simple-icons) -->
  <g>
${rects.map((r) => `    <rect x="${r.x}" y="${r.y}" width="1" height="1" fill="${r.fill}"/>`).join('\n')}
  </g>
</svg>
`;
}

async function generateFromSimpleIcons() {
  const browser = await puppeteer.launch({
    executablePath: '/usr/bin/google-chrome',
    args: ['--no-sandbox', '--disable-dev-shm-usage'],
  });
  const page = await browser.newPage();
  const results = [];
  for (const [key, exportName] of Object.entries(SIMPLE_ICONS)) {
    const icon = icons[exportName] ?? icons[`si${exportName}`];
    if (!icon) throw new Error(`simple-icons 无 ${exportName}（${key}）`);
    const grid = await rasterize(page, icon.path, icon.hex);
    if (!grid) throw new Error(`${key} 栅格化失败`);
    const file = path.join(outDir, `${key}.svg`);
    writeFileSync(file, gridToSvg(grid, icon.hex));
    console.log(`ok ${file}（${icon.title} #${icon.hex}）`);
    results.push(key);
  }
  await browser.close();
  return results;
}

// ---- 2. 手绘字符画兜底（无 simple-icons 收录的品牌） ----

function toSvg(art, palette, key) {
  if (art.length !== 16 || art.some((row) => row.length !== 16)) {
    throw new Error(`${key}: 画布必须为 16×16`);
  }
  const rects = [];
  art.forEach((row, y) => {
    for (let x = 0; x < 16; x++) {
      const ch = row[x];
      if (ch === '.') continue;
      const fill = palette[ch];
      if (!fill) throw new Error(`${key}: 字符 "${ch}" 无对应颜色`);
      rects.push(`    <rect x="${x}" y="${y}" width="1" height="1" fill="${fill}"/>`);
    }
  });
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" shape-rendering="crispEdges">
  <!-- generated by tools/gen-brands.mjs (hand-drawn) -->
  <g>
${rects.join('\n')}
  </g>
</svg>
`;
}

const HAND_DRAWN = {
  // DeepSeek Harness —— 蓝鲸「大肥鱼」
  dsh: {
    palette: { '#': '#123a5c', B: '#2d7ab8', L: '#8ecae6', W: '#cfe8f7', E: '#08263f', S: '#dff3fb', F: '#1b5680' },
    art: [
      '................',
      '................',
      '..........S.....',
      '.........SSS....',
      '.........S.S....',
      '...#########....',
      '..#BBBBBBBBB#...',
      '.#BBBBBBBBBBB#..',
      '#BBBBBBBBBBBBB#.',
      '#BBBWWBBBBBEEB#.',
      '#BBWWBBBBBBBBB#.',
      '#BBBBBBBBBBBB#..',
      '#BLLLLLLLLBB#...',
      '.#LLLLLLLLL#....',
      '..##.###.##.....',
      '.#F#.....#F#....',
    ],
  },

  // 兜底：终端窗口 + 绿色提示符
  generic: {
    palette: { '#': '#5c4a32', R: '#c0392b', K: '#1e2b1e', G: '#4ade80', D: '#22c55e' },
    art: [
      '................',
      '..############..',
      '.#RRRRRRRRRRRR#.',
      '.##############.',
      '.#KKKKKKKKKKKK#.',
      '.#KKKKKKKKKKKK#.',
      '.#KKGKKKKKKKKK#.',
      '.#KKKGGKKKKKKK#.',
      '.#KKKKKDDDDKKK#.',
      '.#KKKKKKKKKKKK#.',
      '.#KKKKKKKKKKKK#.',
      '.#KKKKKKKKKKKK#.',
      '.#KKKKKKKKKKKK#.',
      '.##############.',
      '..############..',
      '................',
    ],
  },

  // OpenAI Codex —— OpenAI 商标未收录 simple-icons，手绘六瓣花结
  codex: {
    palette: { '#': '#0d2440', O: '#10a37f', W: '#e6f6f1' },
    art: [
      '................',
      '.....######.....',
      '...##OOOOOO##...',
      '..#OOOWWWWOOO#..',
      '..#OOW#..#WOO#..',
      '.#OOW#....#WOO#.',
      '.#OW#..##..#WO#.',
      '.#OW#.#WW#.#WO#.',
      '.#OOW#....#WOO#.',
      '..#OOW#..#WOO#..',
      '..#OOOWWWWOOO#..',
      '...##OOOOOO##...',
      '.....######.....',
      '................',
      '................',
      '................',
    ],
  },

  // Goose —— 白鹅（Block Goose 未收录）
  goose: {
    palette: { '#': '#4a4436', W: '#f5f0e6', O: '#f59e0b', E: '#1c1917', G: '#e7e0cf' },
    art: [
      '................',
      '................',
      '.....##.........',
      '....#WW#..##....',
      '....#WW##WW#....',
      '....#WWEWWW#....',
      '.....#WWWW#.....',
      '#....#WWWW#.....',
      '#O##.#WWWW#.....',
      '.#OWWWWWWWW#....',
      '..#WWWWWWWWW#...',
      '..#WWWWWWWWW#...',
      '...#WWWWWWW#....',
      '...#W##W##W#....',
      '....#..#..#.....',
      '................',
    ],
  },

  // Amp —— 闪电（Sourcegraph Amp 无独立收录）
  amp: {
    palette: { '#': '#1a2b4a', O: '#22d3ee', W: '#a5f3fc' },
    art: [
      '................',
      '.......###......',
      '......#OOO#.....',
      '.....#OOO#......',
      '....#OOO#.......',
      '...#OOO#........',
      '..#OOO#####.....',
      '.#OOOOOOOOO#....',
      '..####OOOO#.....',
      '......#OO#......',
      '.....#OO#.......',
      '....#OO#........',
      '...#OO##........',
      '..#OO#..........',
      '..##............',
      '................',
    ],
  },

  // Aider —— 棋子（未收录）
  aider: {
    palette: { '#': '#3d2b1f', O: '#d97706', W: '#fde68a', G: '#92400e' },
    art: [
      '................',
      '.....######.....',
      '....#OOOOOO#....',
      '...#OOWWWWOO#...',
      '...#OOWWWWOO#...',
      '....#OOOOOO#....',
      '.....#OOOO#.....',
      '.....#OOOO#.....',
      '....#OOOOOO#....',
      '...#OOGGGGOO#...',
      '..#OOOGGGOOOO#..',
      '.#OOOOOGGOOOOO#.',
      '..##############',
      '..##############',
      '................',
      '................',
    ],
  },
};

function generateHandDrawn() {
  let n = 0;
  for (const [key, { art, palette }] of Object.entries(HAND_DRAWN)) {
    const file = path.join(outDir, `${key}.svg`);
    writeFileSync(file, toSvg(art, palette, key));
    console.log(`ok ${file}（hand-drawn）`);
    n++;
  }
  return n;
}

const fromIcons = await generateFromSimpleIcons();
const drawn = generateHandDrawn();
console.log(`generated ${fromIcons.length} simple-icons + ${drawn} hand-drawn brand avatars`);
